[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_TITLE = "Creative Struggle"
  NODE_ENV = "development"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 