// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbnrlavbpnbqdakootap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibnJsYXZicG5icWRha29vdGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjUxMzQsImV4cCI6MjA1NjYwMTEzNH0.-aoJrPQTN-MzWvGmzMJhJ0HSFqkebAcgZ1u6RFW10qY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);